### PR TITLE
Zack bumpous

### PR DESCRIPTION
**Pull request by zackychan97**

### CODE REVIEW

**Comment by proateen** [comment]
Mate, he clearly doesn't accept pull requests, just stop.

**Comment by zackychan97** [comment]
It was a mistake!! Relax. I'm sorry. I closed it myself to right after too
lol. Jeesh.

**Comment by zackychan97** [comment]
So mate, if you would have checked to see if it was closed before you
responded, you would have like, not had to write this at all. Kind regards,
lulz.

**Comment by zackychan97** [comment]
And if you're looking in the pull request history... yeah I've literally
closed all of my own seconds after making it, and plus you can always
revert a merge anyways (never came to that). Some of us don't have the best
internet/computers btw. That is the last I am going to comment on this bc
you just came off as ultra arrogant, basically the epitome of a tech bro.

**Pull request closed without merging**
